//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureDataSender_FEZ_Feather
{
    
    internal partial class ResourcesSecret
    {
        private static System.Resources.ResourceManager manager;
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((ResourcesSecret.manager == null))
                {
                    ResourcesSecret.manager = new System.Resources.ResourceManager("AzureDataSender_FEZ_Feather.ResourcesSecret", typeof(ResourcesSecret).Assembly);
                }
                return ResourcesSecret.manager;
            }
        }
        internal static string GetString(ResourcesSecret.StringResources id)
        {
            return ((string)(ResourceManager.GetObject(((short)(id)))));
        }
        [System.SerializableAttribute()]
        internal enum StringResources : short
        {
            SSID_1 = -29313,
            AzureAccountName = -17596,
            Key_1 = -15014,
            Key_2 = -15013,
            AzureAccountKey = -13890,
            SSID_2 = 13126,
        }
    }
}
